version: '3.3'
services:
  ms25-pg:
    container_name: ms25-db
    image: mysql
    ports:
      - "3336:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - ms25


  adminer:
    image: adminer
    ports:
      - "9090:8080"
    networks:
      - ms25





volumes:
  my-datavolume:

networks:
  ms25:
