spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3336}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver





server:
  port: 8081
  servlet:
    context-path: /lesson2




